### ISSUE TITLE
Share data from a step to another

### ISSUE THREAD

**Issue by rajivenator** [fcannizzaro/material-stepper#1]
HI can you guide me how to pass data from one step to another and also avoid loading the next step before first step is complete.

**Comment by fcannizzaro** [comment]
Hello! 

> avoid loading the next step before first step is complete

override these two methods

```java
   
@Override
public boolean nextIf() {
	return conditionForCompleteStep;
}


@Override
public String error() {
	return "<b>Not yet Completed</b>";
}

```


>  how to pass data from one step to another

in step **1**

```java

Bundle data = mStepper.getExtras();

data.putInt("MyData", 5);
data.putString("MyKey", "data");
```

in step **2**

```java

Bundle data = mStepper.getExtras();

int myData = data.getInt("MyData");
String myKey = data.getString("MyData");
```
for example you can retrieve first step data in ```onStepVisible``` method

```java
@Override
public void onStepVisible() {
   // here
}

```

**Comment by ismaeltoe** [comment]
How to pass data from the TabStepper Activity to the first step?

**Comment by ismaeltoe** [comment]
Got the solution

**Comment by sophiefonseca** [comment]
Hello. I tried overriding those methods but the next step is still loaded. Can you please help me? I'm struggling for a whole day just to get this right..
