### ISSUE TITLE
toolbar?

### ISSUE THREAD

**Issue by TheLoyalCruel** [fcannizzaro/material-stepper#13]
Hi 
thanks for the library
is there any way to use toolbar in this lib?

**Comment by amouly** [comment]
@TheLoyalCruel the only way I've found is creating the activity and using the default AppCompat theme, for example: "Theme.AppCompat.Light.DarkActionBar".

**Comment by VioletGiraffe** [comment]
This is a problem.

**Comment by xbroak** [comment]
Any update on this?

**Comment by fcannizzaro** [comment]
In 1.1.8 you can use getToolbar() method.
