### ISSUE TITLE
ProgressBar - translations

### ISSUE THREAD

**Issue by juniorJaffa** [fcannizzaro/material-stepper#16]
Hi, is possible to set PREV, NEXT, COMPLETE by my own strings/translations?

> string name="ms_prev">PREV</string

> string name="ms_next">NEXT</string

> string name="ms_end">COMPLETE</string

**Comment by fcannizzaro** [comment]
yes

**Comment by juniorJaffa** [comment]
:D Great but how? snippet code?

**Comment by fcannizzaro** [comment]
in your xml project files add

<string name="ms_next">CUSTOM NEXT</string>

**Comment by juniorJaffa** [comment]
Thanks much, I checked your source but did not get that just "overriding" helps.

**Comment by RubenSolerAlvarez** [comment]
Hi, is possible to set custom typeface to PREV, NEXT, COMPLETE buttons?

**Comment by RubenSolerAlvarez** [comment]
thanks in advanced

**Comment by RubenSolerAlvarez** [comment]
I think the aswer is: 

TextView next = (TextView)findViewById(R.id.stepNext);
Typeface font = Typeface.createFromAsset(getAssets(),"mytypeface.ttf");
next.setTypeface(font);

;)
