### ISSUE TITLE
Bugs found

### ISSUE THREAD

**Issue by Cheomm88** [fcannizzaro/material-stepper#20]
Hello,
first of all just say thank you!! Your library and examples helped me a lot making an app with dots steps. :+1: :+1: :+1: 

I have found two bugs:

1. If I press really fast from the last step "Back" until the first step, the step will appear in a bad position, seems to be related with the animation or similar.

2. This bug is worse, in my code I use mStepper for example TextView textView = new TextView(mStepper) but if I rotate my device to landspace the function is recalled and now mStepper is null (java.lang.NullPointerException), and the app crashes.

(BTW The 2nd I am not using the landspace on my app, so I have set only portrait mode.)

**Comment by fcannizzaro** [comment]
1) #30 
2) Using v 1.1.3 does it keep crashing?

**Comment by Cheomm88** [comment]
Hi @fcannizzaro 
1) I just press next and back, not swiping between screens.
2) I just update to v1.1.3 and it doesnt crash :)

Great job @fcannizzaro !! Keep in this way ^^
