### ISSUE TITLE
Hardcoded "Optional" word

### ISSUE THREAD

**Issue by amouly** [fcannizzaro/material-stepper#21]
The "Optional" word it's hardcoded in the main parent class, and it's not using the resource String. This should be replaced with "ms_optional" resource.

[Code](https://github.com/fcannizzaro/material-stepper/blob/9e994df43ddd05b60e9b7ff2511edab2eaf14079/library/src/main/java/com/github/fcannizzaro/materialstepper/AbstractStep.java#L22)

Thanks for this amazing lib :).

**Comment by fcannizzaro** [comment]
Yeah I forgot it.

**Comment by fcannizzaro** [comment]
fixed in v. [1.0.9](https://github.com/fcannizzaro/material-stepper/releases/tag/1.0.9)

**Comment by alashow** [comment]
@fcannizzaro This fix is buggy. see pullrequest. see #30 commits
