### ISSUE TITLE
Orientation Changes?

### ISSUE THREAD

**Issue by orpnoch** [fcannizzaro/material-stepper#27]
Hello,
it's a nice Library and very easy to use. but, it will be perfect if it could handles orientation changes.

Is there a way to handle orientation changes?

thank you.

**Comment by tamsir** [comment]
Hello orpnoch,
Try to combine with this library https://github.com/frankiesardo/icepick

**Comment by orpnoch** [comment]
@tamsir the problem is I can't get any reference to the fragments. They get recreated on the main activity.

**Comment by tamsir** [comment]
Okay,
You use the last version (1.0.9) ?

**Comment by orpnoch** [comment]
Yes, I use the last version.

**Comment by tamsir** [comment]
I have the same problem with this version. Try using the 1.0.8
I think it's the same probem #25

**Comment by fcannizzaro** [comment]
Using v 1.1.3 does it keep crashing?

**Comment by tamsir** [comment]
Cool, it works now.
Thanks for solving the bug
