### ISSUE TITLE
FragmentStatePagerAdapter alternative?

### ISSUE THREAD

**Issue by amouly** [fcannizzaro/material-stepper#31]
The base stepper it's using a FragmentPagerAdapter, which it's cool but it doesn't retain the state of Fragment. Could be have an alternative Adapter, but extending FragmentStatePagerAdapter which manages the state of Fragment?

Thanks.

**Comment by fcannizzaro** [comment]
fixed in 1.1.2 (57a160c7caa01c912743d60d6f7b5f1e86bfaac3)

**Comment by amouly** [comment]
@fcannizzaro wait, we should provide both Adapters some way, I don't think replacing the old adapter with StateAdapter will be good, maybe it cause some side-effect.

**Comment by fcannizzaro** [comment]
Check now (37eaffc2fc00e9ca26f84ce735592d6d7063f8c3).
