### ISSUE TITLE
Suggestions for passing the result of a step to the next step

### ISSUE THREAD

**Issue by toadzky** [fcannizzaro/material-stepper#32]
I do immutable data objects, so when I finish a form on one step, I want to pass the result to the next step. I don't see any way to do that built in, and I'd be happy to implement something and throw a PR your way if there isn't an established way of doing it.

**Comment by fcannizzaro** [comment]
Hi check v 1.1.5 [README](https://github.com/fcannizzaro/material-stepper#share-data-between-steps)
