### ISSUE TITLE
Button View on First Page

### ISSUE THREAD

**Issue by Biggo6** [fcannizzaro/material-stepper#33]
Hello Buddy

i would like to thank you for your nice library but i wounder if there is any means on putting button on first page see the figure below

![capture](https://cloud.githubusercontent.com/assets/4988463/15144857/c70fb38a-16ba-11e6-9710-9bd81056f601.PNG)

**Comment by fcannizzaro** [comment]
Yeah on the next release

**Comment by fcannizzaro** [comment]
Check [v1.1.6](https://github.com/fcannizzaro/material-stepper/releases/tag/1.1.6)

You can show previous button on first step using "setStartPreviousButton()"
