### ISSUE TITLE
Get Data on Next 

### ISSUE THREAD

**Issue by Biggo6** [fcannizzaro/material-stepper#34]
Hello Buddy

i struggled the whole day figuring out on how to access fragment views data on next clicked but i could not please assign here are my codes
![2](https://cloud.githubusercontent.com/assets/4988463/15155366/d4bdc26c-16ea-11e6-9063-735cd8425c4c.PNG)
![3](https://cloud.githubusercontent.com/assets/4988463/15155367/d518e610-16ea-11e6-9b95-23a7b99bb225.PNG)

as u can see below also
![6](https://cloud.githubusercontent.com/assets/4988463/15155461/32273ec4-16eb-11e6-9f86-1cc9e393649d.PNG)

**Comment by fcannizzaro** [comment]
Check [v1.1.6](https://github.com/fcannizzaro/material-stepper/releases/tag/1.1.6)

You can now override onNext method and pass data to next step
