### ISSUE TITLE
Get Data from Last Page 

### ISSUE THREAD

**Issue by Biggo6** [fcannizzaro/material-stepper#35]
Hello 

i wounder if i can get data of last page/stepper (fragment) which displays COMPLETE button, i mean 

is there method like **getLastStepData()**  rather than **getStepDatafor(int step)
**
![09](https://cloud.githubusercontent.com/assets/4988463/15173259/c4418b52-1763-11e6-9cdd-a8fa5d831942.PNG)

**Comment by fcannizzaro** [comment]
You can use mStepper.getExtras(), edit the bundle and get data onComplete()
