### ISSUE TITLE
TextStepper  wrong number in title

### ISSUE THREAD

**Issue by MFlisar** [fcannizzaro/material-stepper#43]
This code is wrong (v1.1.8):

        int next = this.mSteps.current() < this.mSteps.total() - 1?this.mSteps.current() + 1:this.mSteps.current();
        this.mCounter.setText(this.mText.replace("$current", String.valueOf(next)).replace("$total", String.valueOf(this.mSteps.total())));

Because then the title will display for example "Step 7 of 8" for Step 8 instead of "Step 8 of 8"...

**Comment by fcannizzaro** [comment]
see #44
