### ISSUE TITLE
Failed to resolve: com.github.fcannizzaro:material-stepper:1.1.9 

### ISSUE THREAD

**Issue by KKChong** [fcannizzaro/material-stepper#44]
i just upgraded to 1.1.9 from 1.1.8 and i got this error "Failed to resolve: com.github.fcannizzaro:material-stepper:1.1.9 "

**Comment by fcannizzaro** [comment]
I can't understand why Jitpack won't build , however [here][(https://github.com/fcannizzaro/material-stepper/releases/tag/1.1.9) you can find the jar lib.

**Comment by sirvon** [comment]
thank you for the lib!

Jars are so unacceptable in this CI/Automaton/Event based day in age we are developing in.
Your lib will prosper more with a copy/paste only distribution mechanism.

**Comment by fcannizzaro** [comment]
Jitpack now works (1.2.1)
