### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by epetrenko** [fcannizzaro/material-stepper#5]
Hi. Could you release to a public maven central repository for easier usage and to avoid including library sources in project.

To support easier including in build.gradle: 
```
dependencies {
     compile "com.github.fcannizzaro.material-stepper:${version}"
}
```

**Comment by fcannizzaro** [comment]
Done [check here](https://github.com/fcannizzaro/material-stepper#dependency)

**Comment by epetrenko** [comment]
Thanks!
